# Generated by Django 4.2.7 on 2025-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examsession_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_user_exam_session',
        ),
        migrations.AddField(
            model_name='examsession',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('user', 'exam', 'attempt_number'), name='unique_user_exam_attempt'),
        ),
    ]
